version: '3'
services:
  nginx-proxy:
    image: upstreamable/nginx-proxy:alpine
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /data/letsencrypt/certs:/etc/nginx/certs:ro
      - /data/letsencrypt/vhost.d:/etc/nginx/vhost.d
      - /data/letsencrypt/html:/etc/nginx/html
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /data/letsencrypt/conf.d:/etc/nginx/conf.d
      - /data/letsencrypt/vhost.d:/etc/nginx/vhost.d
      - /data/letsencrypt/html:/usr/share/nginx/html
      - /data/letsencrypt/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      VIRTUAL_HOST: '${HOST:-localhost}'
      VIRTUAL_PATH: '.well-known/acme-challenge'
  api:
    build: api
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      VIRTUAL_HOST: '${HOST:-localhost}'
      VIRTUAL_PATH: '/api'
      MODE: 'Production'
      DATABASE_URL: 'postgres://postgres:${POSTGRES_PASSWORD}@postgres'
      SECRET_KEY: '${SECRET_KEY}'
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: '${HOST:-localhost}'
      VIRTUAL_PATH: '/'
      LETSENCRYPT_HOST: 'isaac.zafuta.com'
      LETSENCRYPT_EMAIL: 'isaac@zafuta.com'
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /data/postgres:/var/lib/postgresql/data
