version: '3'
services:
  frontend:
    volumes:
      - ./frontend:/usr/src/app
    command: ["yarn", "start"]
  api:
    volumes:
      - ./api:/usr/src/app
    environment:
      MODE: 'Development'
